# defaults:
#     - override hydra/launcher: submitit_local

# environment
benchmark: dm_control
task: CheetahRun
obs: state
exp_name : test
# evaluation
checkpoint: ???
eval_episodes: 1
eval_pi: true
eval_value: true # evaluate value function approximation
eval_freq: 50000
impl : warp # valid: warp, jax, cpp
eval_with_training_env : false #used by gmmtd3
#policy
policy : td3
asymmetric_critic: true
dr_augmented_critic: true
distributional_q : false
use_tuned_reward: false

#dynamics shift
randomization: true
# shift_dynamics_type: stochastic 
eval_randomization: true
# logging
wandb_project: test-algorithms
wandb_entity: tjrcjf410-seoul-national-university
wandb_group_prefix: ''
wandb_group: ''
wandb_silent: false
use_wandb: true
save_csv: true
comment: ''

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

#default parameters
# learning_rate: 3e-4
# discounting: 0.99
# action_repeat: 1
# normalize_observations: true
# reward_scale: 1.0
batch_size : ???

#wasserstein q-learning
n_nominals : ???
delta : ???
lambda_update_steps : ???
single_lambda : false
lmbda_lr : ???
init_lmbda : 1.
distance_type : wass
dr_train_ratio : 1.0

#simba
simba : false

#m2td3
omega_distance_threshold: 0.1

#bridgetd3
bridge_alpha: 1.0
bridge_auto_alpha: false
bridge_target_kinetic_coef: 2.5
bridge_init_log_alpha: null
bridge_alpha_lr: null
adversary_learning_rate: null

#gmmtd3
beta: 1.0

#TCRMDP
radius: 0.001
rarl_range_scale: 0.5
omniscient_adversary: true
